services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    # ports: we don't need to expose the port, we will use ZeroTier
    # - "3030:8080"
    environment:
      - OPENAI_API_KEY=REPLACE_WITH_YOUR_OPENAI_API_KEY
    volumes:
      - REPLACE_WITH_YOUR_BACKEND_DATA_PATH:/app/backend/data
      - REPLACE_WITH_YOUR_ZEROTIER_PATH:/var/lib/zerotier-one  # ZeroTier data
      # Example:
      # - /media/frans/frans-docker/docker/openwebui:/app/backend/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    healthcheck:
      test: ["CMD", "/zerotier-init.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - default

networks:
  default:
    driver: bridge
