services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    # ports: we don't need to expose the port, we will use ZeroTier
    # - "3030:8080"
    environment:
      - OPENAI_API_KEY=REPLACE_WITH_YOUR_OPENAI_API_KEY
      - PUID=1000
      - PGID=1000
    volumes:
      - REPLACE_WITH_YOUR_BACKEND_DATA_PATH:/app/backend/data
      - REPLACE_WITH_YOUR_ZEROTIER_PATH:/var/lib/zerotier-one  # ZeroTier data
      # Example:
      # - /media/frans/frans-docker/docker/openwebui/backend-data:/app/backend/data
      # - /media/frans/frans-docker/docker/openwebui/zerotier-one:/var/lib/zerotier-one
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    healthcheck:
      test: ["CMD", "/zerotier-init.sh"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - default
  nginx-open-webui:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx:latest
    container_name: nginx-open-webui
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - REPLACE_WITH_YOUR_NGINX_CONF:/etc/nginx/conf.d/default.conf
      - REPLACE_WITH_YOUT_ZEROTIER_PATH:/var/lib/zerotier-one  # ZeroTier data
      - REPLACE_WITH_YOUT_NGINX_SSL:/etc/nginx/ssl
      # Example:
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - /media/frans/frans-docker/docker/openwebui/zerotier-one-nginx:/var/lib/zerotier-one
      # - ./nginx-ssl:/etc/nginx/ssl
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    healthcheck:
      test: ["CMD", "/zerotier-init.sh"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - default
networks:
  default:
    driver: bridge
